version: '3.8'

services:
  attendance-backend:
    build: .
    container_name: school_attendance_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      DATA_FILE: /app/backend/school_data.json
    volumes:
      - ./backend/school_data.json:/app/backend/school_data.json
